model:
  type: FCMNIST

dataset:
  dataset: mnist
  num_clients: 50
  alpha: 0.5
  batch_size: 64
  partition_type: non_iid

training:
  global_epochs: 20
  local_epochs: 3
  learning_rate: 0.001
  sampled_clients: 40
  local_DP_SGD: false
  fedprox: false
  fedprox_mu: 0.01
  optimizer: SGD
  momentum: 0.9

attack:
  attack: min_max
  num_attackers: 10

system:
  seed: 42

aggregation:
  aggregation_strategy: fedavg