federated_learning:
  global_epochs: 4
  local_epochs: 5
  learning_rate: 0.01
  num_clients : 50
  sampled_clients : 30
  alpha : 0.5
  batch_size: 32
  aggregation_strategy: 'TRIM_MEAN'
  partition_type : 'non-iid'
  seed: 42
  dataset: 'mnist'
model:
  type: 'FCMNIST'
server:
  save_path: '/c:/Users/39340/KBTS/models/global_model.pth'