federated_learning:
  aggregation_strategy: KeTS
  alpha: 0.55
  attack: MIN_MAX
  batch_size: 64
  dataset: mnist
  global_epochs: 5
  learning_rate: 0.001
  local_DP_SGD: false
  local_epochs: 4
  num_attackers: 10
  num_clients: 50
  partition_type: non-iid
  sampled_clients: 40
  seed: 42
model:
  type: FCMNIST
