federated_learning:
  aggregation_strategy: MEDIAN
  alpha: 0.5
  attack: MIN_MAX_V2
  batch_size: 64
  dataset: fashion_mnist
  global_epochs: 30
  learning_rate: 0.001
  local_epochs: 4
  num_attackers: 15
  num_clients: 50
  partition_type: non-iid
  sampled_clients: 50 #all
  seed: 42
  local_DP_SGD: False
model:
  type: FNet


